### ISSUE TITLE
OCI Image failing

### ISSUE THREAD

**Issue by TheChymera** [con/opfvta-reexecution#68]
Any idea why this could be happening?

```
[deco]~/docsrc/opfvta-reexecution ❱ make analysis-oci OCI_BINARY=podman
Makefile:126: warning: overriding recipe for target 'article-upload'
Makefile:122: warning: ignoring old recipe for target 'article-upload'
podman run \
	-it \
	--rm \
	-v /home/chymera/docsrc/opfvta-reexecution:/opt \
	-v /home/chymera/docsrc/opfvta-reexecution/inputs/opfvta_bidsdata:/usr/share/opfvta_bidsdata \
	-v /home/chymera/docsrc/opfvta-reexecution/inputs/mouse-brain-templates/mouse-brain-templates:/usr/share/mouse_brain_atlases \
	-v /home/chymera/docsrc/opfvta-reexecution/scratch:/root/.scratch \
	-v /home/chymera/docsrc/opfvta-reexecution/code/empty:/opfvta/ \
	--workdir /opt/code \
	docker.io/centerforopenneuroscience/opfvta:2.0.0-alpha \
	./produce-analysis.sh podman
Trying to pull docker.io/centerforopenneuroscience/opfvta:2.0.0-alpha...
Getting image source signatures
Copying blob 9c8b092db661 done   |
Copying blob 1d2f15ad72ce done   |
Copying blob ffffc0e2a3ab done   |
Copying blob f118e048a998 done   |
Copying blob 22257a3b41cb done   |
Copying blob d40bc7c76dfc done   |
Copying blob 3fa9af69253b done   |
Copying blob d0357dd7df70 done   |
Copying blob b0997c2b04e1 done   |
Copying blob 24796a507169 done   |
Copying blob 4864d89a0924 done   |
Copying blob a2bab9d328ac done   |
Copying blob db9e31424582 done   |
Copying blob 94f94abb0c40 done   |
Copying blob 15eca9182579 done   |
Copying blob 9349324651f9 done   |
Copying blob 517dc88d21cd done   |
Copying blob 2e6b331b4bb0 done   |
Copying config f6dc42743f done   |
Writing manifest to image destination
/opt/code/opfvta /opt/code
rubber --clean article.tex
removing tree pythontex-files-article
removing tree pythontex-files-article
rm _minted-article -rf
rubber --clean pitch.tex
removing tree pythontex-files-pitch
removing tree pythontex-files-pitch
rm _minted-pitch -rf
rubber --clean review.tex
removing tree pythontex-files-review
rm _minted-review -rf
pushd prepare && ./run.sh
/opt/code/opfvta/prepare /opt/code/opfvta
!!! Repository 'gentoo' has sync-uri attribute, but is missing sync-type attribute
Failed to import duecredit due to No module named 'duecredit'
/usr/lib/python3.10/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
/usr/lib/python3.10/site-packages/bids/layout/bids_layout.py:116: UserWarning: 'dataset_description.json' file is missing from project root. You may want to set the root path to a valid BIDS project.
  warnings.warn("'dataset_description.json' file is missing from "
Traceback (most recent call last):
  File "/opt/code/opfvta/prepare/preprocess.py", line 17, in <module>
    generic(bids_base,
  File "/usr/lib/python3.10/site-packages/samri/pipelines/preprocess.py", line 392, in generic
    bids_base, out_base, out_dir, template, registration_mask, data_selection, functional_scan_types, structural_scan_types, subjects_sessions, func_ind, struct_ind = common_select(
  File "/usr/lib/python3.10/site-packages/samri/pipelines/preprocess.py", line 734, in common_select
    data_selection = bids_data_selection(bids_base, structural_match, functional_match, subjects, sessions)
  File "/usr/lib/python3.10/site-packages/samri/pipelines/utils.py", line 240, in bids_data_selection
    df = df[~df.path.str.contains(base + ".*/\.")]
  File "/usr/lib/python3.10/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
  File "/usr/lib/python3.10/site-packages/pandas/core/accessor.py", line 182, in __get__
    accessor_obj = self._accessor(obj)
  File "/usr/lib/python3.10/site-packages/pandas/core/strings/accessor.py", line 181, in __init__
    self._inferred_dtype = self._validate(data)
  File "/usr/lib/python3.10/site-packages/pandas/core/strings/accessor.py", line 235, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!. Did you mean: 'std'?
make: *** [Makefile:55: data] Error 1
make: *** [Makefile:76: analysis-oci] Error 2
```

**Comment by TheChymera** [comment]
Also, I can't figure out why the article generation code is executed by the `analysis-oci` target:

from the above:

```
...
rubber --clean article.tex
removing tree pythontex-files-article
removing tree pythontex-files-article
rm _minted-article -rf
rubber --clean pitch.tex
removing tree pythontex-files-pitch
removing tree pythontex-files-pitch
rm _minted-pitch -rf
rubber --clean review.tex
removing tree pythontex-files-review
rm _minted-review -rf
pushd prepare && ./run.sh
...
```

this part shouldn't be happening.

**Comment by yarikoptic** [comment]
<details>
<summary>in a repo I found on laptop - it didn't fail</summary> 

```shell
removing tree pythontex-files-review
rm _minted-review -rf
pushd prepare && ./run.sh
/opt/code/opfvta/prepare /opt/code/opfvta
!!! Repository 'gentoo' has sync-uri attribute, but is missing sync-type attribute
Failed to import duecredit due to No module named 'duecredit'
/usr/lib/python3.10/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:283: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:296: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
/usr/lib/python3.10/site-packages/samri/pipelines/utils.py:335: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_df = res_df.append(_df)
                                                   path modality subject session  ...        acq  run  type scan_type
1917  /root/.scratch/opfvta/bids/sub-6257/ses-ofM/fu...      cbv    6257     ofM  ...        EPI    0  func          
1915  /root/.scratch/opfvta/bids/sub-6257/ses-ofM/an...      T2w    6257     ofM  ...  TurboRARE  NaN  anat          
1923  /root/.scratch/opfvta/bids/sub-6259/ses-ofM/fu...      cbv    6259     ofM  ...        EPI    0  func          
1928  /root/.scratch/opfvta/bids/sub-6259/ses-ofMr1/...      cbv    6259   ofMr1  ...        EPI    1  func          
1931  /root/.scratch/opfvta/bids/sub-6259/ses-ofMr1/...      cbv    6259   ofMr1  ...        EPI    0  func          
...                                                 ...      ...     ...     ...  ...        ...  ...   ...       ...
2220  /root/.scratch/opfvta/bids/sub-6654/ses-ofMr1/...      T2w    6654   ofMr1  ...  TurboRARE  NaN  anat          
2228  /root/.scratch/opfvta/bids/sub-6655/ses-ofM/fu...      cbv    6655     ofM  ...        EPI    0  func          
2233  /root/.scratch/opfvta/bids/sub-6655/ses-ofMr1/...      cbv    6655   ofMr1  ...        EPI    0  func          
2226  /root/.scratch/opfvta/bids/sub-6655/ses-ofM/an...      T2w    6655     ofM  ...  TurboRARE  NaN  anat          

```
</details>

and it lacked 

```
/usr/lib/python3.10/site-packages/bids/layout/bids_layout.py:116: UserWarning: 'dataset_description.json' file is missing from project root. You may want to set the root path to a valid BIDS project.
  warnings.warn("'dataset_description.json' file is missing from "
```

so possible I have some `dataset_description.json` you don't have... but I see only `./inputs/opfvta_bidsdata/dataset_description.json` and I have it and I guess you do too?  if not -- did you install subdatasets? (we discovered that gettting that data gets only atlas, not bids data)...

**Comment by TheChymera** [comment]
This seems to be triggered by failing to download the data. Pretty cryptic error message.
